### ISSUE TITLE
WS280 14:  Split file is partial

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#137] opened 2021-03-03 13:44 UTC
When splitting ace files to load them in batches, they often crash, quite often because of a miss-placed quote eg " or ' . The lines left are incomplete, and it is uncertain if/how much of the data is loaded.
STEP:

map_RNAi.pl.WS280.20862
map_RNAi.pl -store /nfs/panda/ensemblgenomes/wormbase/BUILD/autoace/Elegans.store
ERROR while parsing ACE file /nfs/panda/ensemblgenomes/wormbase/BUILD/autoace/tmpace/RNAi_mappings.ace_split_26
// ERROR - object parse error, near line 0 while parsing "Gene : WBGene00303369", error was: Unknown tag "Inferred_automati"

The job finished anyway, but it is possible that the partial file meant that not all data was ingested. Unclear how the script managed to continue after these errors.

Action:
1. Re-write the splitting script to clean up single/double quotes, eg do a backslash to comment out uneven numbers. 
2. Check that the process of splitting the files have not introduced errors (eg. sum of split files is the same as the original file), before going on to start loading the files.
3. Test the script on small files with artificially introduced single/double quotes; that the splits happen, and that the files can load into a testing (empty) ACE database.
4. Test that the script works on a big file, like  ls -lS  /nfs/panda/ensemblgenomes/wormbase/BUILD/elegans/acefiles/*.ace | head. Checking the file that caused issues above, the file looks not to have any issues, so it may be that the splitting does not work as expected, or disk glitches is the cause.

**Comment by markquintontulloch** [comment] 2021-03-03 14:12
@MagdalenaZZ - I'm not convinced that changing the splitting script is the correct solution, or even possible.  The splitting is done in the load_to_database subroutine of Wormbase.pm.  The problem is that there's no way of knowing at this stage which quotes are the correct ones and which are erroneous.

e.g. tag_one "This is an entry without a quote" tag_two "This "entry has an erroneous quote"
How does the script reliably know which is the quote mark to escape?

It is far better, in my opinion, to escape the quotes at the point of ace file creation.  That way, you know that ANY quotes need to be commented out.  The disadvantage is that it needs to be done for each script where this can occur.

We could put a check in the file splitting subroutine to ensure that there are an even number of unescaped quotes.  However, how should such entries be dealt with - throw an error and ignore the entry for loading, or stop the loading process altogether?

**Comment by markquintontulloch** [comment] 2021-03-12 12:20
Resolved by commits [2f34d2c](https://github.com/WormBase/wormbase-pipeline/commit/2f34d2c2b13bca57ef585eb18e705fbf2111536a#diff-477a7aebe07a242b1740b08c9d717b82bdea187170ef976cf7bd61daf438997b) and [233c704](https://github.com/WormBase/wormbase-pipeline/commit/233c704def01fb39db533b1ebd74add1222e51b6#diff-477a7aebe07a242b1740b08c9d717b82bdea187170ef976cf7bd61daf438997b)

**Comment by MagdalenaZZ** [comment] 2021-04-08 12:52
We tried to load the file /nfs/production/panda/ensemblgenomes/wormbase/TEST/BUILD/autoace/acefiles/RNAi_mappings.ace which failed. It wrote the log file  /nfs/production/panda/ensemblgenomes/wormbase/TEST/BUILD/autoace/logs/debug/mz3,pad,mqt,skd/map_RNAi.pl.WS666.5772  where one of the split files was incomplete:
ERROR while parsing ACE file /nfs/panda/ensemblgenomes/wormbase/TEST/BUILD/autoace/tmpace/RNAi_mappings.ace_split_26
// ERROR -  object parse error, near line 0 while parsing "Gene : WBGene00009082", error was: Unknown tag "RNAi_re"

Unfortunately, it did not seem to have triggered your  ERROR statement in commit 2f34d2c on line 1128 to be triggered. Could we please go back to your code and re-think how we are doing this test, so that it would be triggered by these types of script failures?

**Comment by MagdalenaZZ** [comment] 2021-04-08 13:07
However, your other test worked perfectly, file  map_tags.pl.WS666.28322 contains your error message:
ERROR: 1 entries not loaded - written to /nfs/panda/ensemblgenomes/wormbase/TEST/BUILD/autoace/acefiles/map_tags_unloaded.ace
The output file it has written is indeed partial, with a missing line-ending. Not sure if there was more to this entry, or not, but we did get the Error message, and the separate file, and the rest of the file seems to have loaded correctly. 
The slight issue we have is that we don't know the whole object that this partial object came from, because the partial bit is so small, so it was hard to "find and rescue" the partial object. But we can perhaps consider it later? It seems like the underlying issue is that the split file we were trying to load was partial, and we were not warned about that in the first place.

**Comment by markquintontulloch** [comment] 2021-04-13 12:34
Changing logic to parse split files after creation and make the following checks:
1.  Uneven number of unescaped quotes (as also implemented when creating the split files)
2.  Check that split files contain 5000 entries (unless last split file, in which case compare against expected nr)

**Comment by markquintontulloch** [comment] 2021-04-15 13:34
Fixed by commits [b62fc34](https://github.com/WormBase/wormbase-pipeline/commit/b62fc348dd4826ac5e1a9e15e6495334ebbd7328#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36) and [d52b60e](https://github.com/WormBase/wormbase-pipeline/commit/d52b60e0e5be9174b42d2fe75d643a09a8025cf5#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36).

I couldn't replicate the partial file error despite repeated test loads of large files, so this ticket may need to be reopened if the error reoccurs and the implemented code fails to catch it and deal with it appropriately.

**Closed by markquintontulloch** 2021-04-15 13:34 UTC
Labels: WS280 Post-mortem
