### ISSUE TITLE
WS280 1: geneace not copied over properly

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#126] opened 2021-02-19 17:09 UTC
**Issue:** geneace was not completely copied to /nfs/production/panda/ensemblgenomes/wormbase/BUILD/PRIMARIES, because this step is not part of the initiate-build script.

**Solution:** We want to make sure the part of the build that copies camace and citace does genace too.

This affects the scripts prepare_primary_databases.pl and unpack_db.pl

1. Fix the initiate-build script to automate copy over geneace again [PAD]
2. When geneace is copied, make sure to wipe out old block files first. [PAD]
3. Update the build guide on this area, and refine the testing [PAD]
4. Testing script updated to verify all 3 databases [MQT]
5. Test that the new scripts work as expected

**Comment by Paul-Davis** [comment] 2021-02-19 17:37
Duplicate of #125

**Closed by Paul-Davis** 2021-02-19 17:37 UTC
Labels: WS280 Post-mortem
